apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.images.wordpress }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.db.host }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.db.name }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.db.user }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpress.db.passwordSecret }}
                  key: {{ .Values.wordpress.db.passwordKey }}
