apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: wordpress
  ports:
    - port: {{ .Values.wordpress.servicePort }}
      targetPort: 80
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: wordpress
  ports:
    - port: {{ .Values.wordpress.servicePort }}
      targetPort: 80
